# file: roles/oracle-java/vars/main.yml
---
java_version: 7u40-b43 # in the form "7u40-b43"
java_tar: "{{ java_type }}-{{ java_version.split('-')[0] }}-{{ ansible_system|lower }}-{{ java_arch }}.tar.gz" # jdk-7u40-linux-x64.tar.gz
java_url: http://download.oracle.com/otn-pub/java/jdk/{{ java_version }}/{{ java_tar }}
curl_opts: "-H 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com'"
java_arch: x64 # i568 or x64
java_type: server-jre # jdk, jre or server-jre
java_tmpdir: /tmp
java_dest: /usr/local/share
java_symlink: /opt/java
